#系统配置
app:
  port: :8000
  is-print: true
  time-format: 2006-01-02 15:04:05

#wx 微信配置
wx:
  token: wxtoken


#tbk 淘宝客配置
tbk:
  #折淘客 http://www.zhetaoke.com/user/open/open_shangpin_id.aspx
  ztk:
    gateway: https://api.zhetaoke.com:10001/api
    app-key:
    sid:
    pid:
    method:
      get-tkl: open_gaoyongzhuanlian_tkl

  #好单库 https://www.haodanku.com/api/detail
  hdk:
    gateway: http://v2.api.haodanku.com
    api-key:
    jd-union-id:
    method:
      jd-link: get_jditems_link

      #订单侠接口  https://www.dingdanxia.com/doc/133/124
  ddx:
    gateway: api.tbk.dingdanxia.com
    api-key:
    method:
      vip-url: vip/url_privilege
  pdd:
    gateway: https://gw-api.pinduoduo.com/api/router
    client-id:
    client-secret: 
